export default {
  ignoreFiles: ["**/*.min.css"],
  rules: {
    "alpha-value-notation": null,
    "annotation-no-unknown": true,
    "at-rule-descriptor-no-unknown": true,
    "at-rule-descriptor-value-no-unknown": true,
    "at-rule-empty-line-before": null,
    "at-rule-no-deprecated": true,
    "at-rule-no-unknown": true,
    "at-rule-no-vendor-prefix": true,
    "block-no-empty": true,
    "color-function-alias-notation": null,
    "color-function-notation": null,
    "color-hex-length": null,
    "color-no-hex": true,
    "color-no-invalid-hex": true,
    "comment-empty-line-before": null,
    "comment-no-empty": true,
    "comment-whitespace-inside": null,
    "custom-property-empty-line-before": null,
    "custom-property-no-missing-var-function": true,
    "declaration-block-no-duplicate-custom-properties": true,
    "declaration-block-no-duplicate-properties": [
      true,
      {
        ignore: ["consecutive-duplicates-with-different-values"],
      },
    ],
    "declaration-block-no-redundant-longhand-properties": true,
    "declaration-block-no-shorthand-property-overrides": true,
    "declaration-block-single-line-max-declarations": null,
    "declaration-empty-line-before": null,
    "declaration-no-important": true,
    "declaration-property-max-values": null,
    "declaration-property-value-no-unknown": true,
    "font-family-name-quotes": null,
    "font-family-no-duplicate-names": true,
    "font-family-no-missing-generic-family-keyword": true,
    "font-weight-notation": null,
    "function-calc-no-unspaced-operator": true,
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-name-case": null,
    "function-no-unknown": true,
    "function-url-no-scheme-relative": true,
    "function-url-quotes": null,
    "hue-degree-notation": null,
    "import-notation": null,
    "keyframe-block-no-duplicate-selectors": true,
    "keyframe-declaration-no-important": true,
    "keyframe-selector-notation": null,
    "length-zero-no-unit": true,
    "lightness-notation": null,
    "max-nesting-depth": null,
    "media-feature-name-no-unknown": true,
    "media-feature-name-no-vendor-prefix": true,
    "media-feature-name-value-no-unknown": true,
    "media-feature-range-notation": null,
    "media-query-no-invalid": true,
    "named-grid-areas-no-invalid": true,
    "no-descending-specificity": null,
    "no-duplicate-at-import-rules": true,
    "no-duplicate-selectors": true,
    "no-empty-source": true,
    "no-invalid-double-slash-comments": true,
    "no-invalid-position-at-import-rule": true,
    "no-irregular-whitespace": true,
    "no-unknown-animations": true,
    "no-unknown-custom-media": true,
    "no-unknown-custom-properties": true,
    "number-max-precision": null,
    "property-no-unknown": true,
    "rule-empty-line-before": null,
    "selector-anb-no-unmatchable": true,
    "selector-attribute-quotes": null,
    "selector-max-attribute": null,
    "selector-max-class": null,
    "selector-max-combinators": null,
    "selector-max-compound-selectors": null,
    "selector-max-id": null,
    "selector-max-pseudo-class": null,
    "selector-max-specificity": null,
    "selector-max-type": null,
    "selector-max-universal": null,
    "selector-no-qualifying-type": [
      true,
      {
        ignore: ["attribute", "class"],
      },
    ],
    "selector-no-vendor-prefix": true,
    "selector-not-notation": null,
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-element-colon-notation": null,
    "selector-pseudo-element-no-unknown": true,
    "selector-type-case": null,
    "selector-type-no-unknown": true,
    "shorthand-property-no-redundant-values": true,
    "string-no-newline": true,
    "syntax-string-no-invalid": true,
    "time-min-milliseconds": null,
    "unit-no-unknown": true,
    "value-keyword-case": null,
    "value-no-vendor-prefix": true,
  },
};
