// This JSON Feed automatically generated by blosxom 2.0
// http://creativecommons.org/licenses/by-nc/2.1/jp/

if (typeof(jsonFeeds) == "undefined") jsonFeeds = new Array();

jsonFeeds["http://hail2u.net/blog/index.json"] = {
  "title": "hail2u.net - Weblog",
  "link": "http://hail2u.net/blog/",
  "id": "tag:hail2u.net,2002:/blog/",
  "author": "Kyo Nagashima (kyo@hail2u.net)",
  "updated": "2006-10-20T00:08:22+0900",
  "subtitle": "移り気な管理人が、気になっていることをアトランダムにいろいろ書き連ねてみるblogです。",
  "generator": "http://www.blosxom.com/?v=2.0",
  "entry": [
    {
      "title": "JSONフィードとか何とか #2",
      "link": "http://hail2u.net/blog/coding/json-feed-or-something-else-2.html",
      "id": "tag:hail2u.net,2006:/coding/json-feed-or-something-else-2",
      "summary": "TypePadがJSONフィードの出力に対応したそうで。JSONフィードってーのはdel.icio.usのJSON Feedsとかで見られる、JSONを利用したRSSやAtomっぽい配信フォーマットで、Pure JavaScriptで扱えるのが最大の特徴。特に仕様なんかは無い(と思う)。かなり昔にこのサイトで妄想として取り上げていたのが現実になった感じ。",
      "author": "Kyo Nagashima (kyo@hail2u.net)",
      "category": "Coding",
      "published": "2006-10-20T00:07:00+09:00"
    },
    {
      "title": "Firefoxで素早くdel.icio.usへ投稿",
      "link": "http://hail2u.net/blog/software/delicious-quick-post-with-firefox.html",
      "id": "tag:hail2u.net,2006:/software/delicious-quick-post-with-firefox",
      "summary": "Firefoxでは各ブックマークにKeywordを割り当てることができ、割り当てたKeywordをロケーション・バーで入力してEnterまたはGoボタンを押すことによってそのブックマークを開くことが出来る。このSmart Keywordsと呼ばれている機能はロケーション・バーから検索エンジンを利用した検索を行う場合などに利用する場合が多いが、Bookmarkletなどを含めどんなブックマークにも割り当てることが出来るので、del.icio.usへ投稿するBookmarkletにKeywordとしてdを指定すると、Alt+D D Enterという連続したキー・タイプでdel.icio.usに投稿できるようになる(Alt+Dはロケーション・バーにフォーカスを当てるショートカット)。知人が見ている時にこれを使ってdel.icio.usにササッと投稿するところを見せつけると「デキる男(女)」を演出できます。",
      "author": "Kyo Nagashima (kyo@hail2u.net)",
      "category": "Software",
      "published": "2006-10-19T00:30:00+09:00"
    },
    {
      "title": "HTMLヘルプのソースを公開",
      "link": "http://hail2u.net/blog/software/htmlhelp-sources.html",
      "id": "tag:hail2u.net,2006:/software/htmlhelp-sources",
      "summary": "HTMLヘルプはHTML Help Workshopで逆コンパイルできるのだけど、抜き出されたHTMLのファイル名がテキトウ極まりないものだったり(うろ覚え)とか色々アレだったと思うので、元にしたHTMLファイルにHTML Help Workshopのプロジェクト・ファイル群を加えてzipアーカイブにまとめ、公開しておくことにした。",
      "author": "Kyo Nagashima (kyo@hail2u.net)",
      "category": "Software",
      "published": "2006-10-17T14:24:00+09:00"
    },
    {
      "title": "設定を外部JavaScriptファイルから読み込む",
      "link": "http://hail2u.net/blog/coding/load-settings-from-external-javascript-file.html",
      "id": "tag:hail2u.net,2006:/coding/load-settings-from-external-javascript-file",
      "summary": "JSONで記述した設定ファイルをどこかのサーバーに置き、それを動的にscript要素を追加するアレで読み込み、適用するという試み。タイトルまんま。設定を保存するということは難しいので、使いどころはとても限られる。Bookmarkletでゴニョゴニョするサイトなんかで細かい指定パラメータの代わりに使うとかが唯一に近い光明。",
      "author": "Kyo Nagashima (kyo@hail2u.net)",
      "category": "Coding",
      "published": "2006-10-11T08:25:00+09:00"
    },
    {
      "title": "del.icio.usのnetworkをツリー状に展開しまくる",
      "link": "http://hail2u.net/blog/coding/labs-hail2u-net-del.icio.us-network.html",
      "id": "tag:hail2u.net,2006:/coding/labs-hail2u-net-del.icio.us-network",
      "summary": "エントリのネタに事欠いたので少し前に作ったdel.icio.usのnetworkをツリー状に展開しまくるモノについて書いてみる。タイトルの通りの代物で、基点となるユーザー名のnetworkをリストにして表示し、それぞれのリスト項目のユーザー名の後ろについている矢印画像をクリックすると、更にそのユーザー名のnetworkをリストにして表示し・・・と、延々とツリー状に展開しまくるもの。",
      "author": "Kyo Nagashima (kyo@hail2u.net)",
      "category": "Coding",
      "published": "2006-10-08T01:42:00+09:00"
    },
    {
      "title": "不明なflavour回避パッチの問題点",
      "link": "http://hail2u.net/blog/blosxom/problem-of-avoiding-unknown-flavour-error-patch.html",
      "id": "tag:hail2u.net,2006:/blosxom/problem-of-avoiding-unknown-flavour-error-patch",
      "summary": "かなり前に書いた不明なflavourというエントリで紹介したパッチは概ねうまく機能しているのだけど、検索エンジンなどで意図しないURLが検索結果に出てきてしまうことがあるという問題が。通常は多くのページでリンクを張られている.htmlで終わるURLの方が圧倒的に強く、Web全体からの検索などではあまり問題にならないが、サイト内検索などではかなりゴミとして目立ってしまう。ので、redirectif_noflavourを使い、存在しないflavourの場合は.htmlで終わるURLにリダイレクトさせることにした。",
      "author": "Kyo Nagashima (kyo@hail2u.net)",
      "category": "Blosxom",
      "published": "2006-10-05T00:19:00+09:00"
    },
    {
      "title": "拝み屋横丁顛末記",
      "link": "http://hail2u.net/blog/media/ogamiya-yokotyou-tenmatsuki.html",
      "id": "tag:hail2u.net,2006:/media/ogamiya-yokotyou-tenmatsuki",
      "summary": "一昨日借りた拝み屋横丁顛末記を一気読みしたらもうツボにはまりすぎでどうにもこうにも。思い出し笑いしてしまったりとか、夢に出てきたりとか。「ネタが凝ってる！」とか「展開がうまい！」とかそういうのは欠片もなくて、ヒトコマで笑いをさらう感じ。シャイニング・ウィザードとか。",
      "author": "Kyo Nagashima (kyo@hail2u.net)",
      "category": "Media",
      "published": "2006-10-04T02:31:00+09:00"
    },
    {
      "title": "XPIパッケージにまとめるバッチ・スクリプト",
      "link": "http://hail2u.net/blog/coding/xpi-packaging-batch-script.html",
      "id": "tag:hail2u.net,2006:/coding/xpi-packaging-batch-script",
      "summary": "作成したFirefoxのExtensionをXPIパッケージにまとめる方法の一つとして、バッチ・スクリプトがHow to create Firefox extensionsでかなり昔から公開されている。これはbuild.batをいちいちコピーしなきゃならなかったりとか.svnフォルダなども含んでしまったりする。それをbuild.batをどこかにおいておけばドラッグ・アンド・ドロップでXPIパッケージが作れるようにしたりとか改造してみた。",
      "author": "Kyo Nagashima (kyo@hail2u.net)",
      "category": "Coding",
      "published": "2006-10-02T12:56:00+09:00"
    },
    {
      "title": "使用しているプラグイン",
      "link": "http://hail2u.net/blog/blosxom/plugins-i-use.html",
      "id": "tag:hail2u.net,2006:/blosxom/plugins-i-use",
      "summary": "43 Foldersの中の人がWordpressで使用しているプラグインをdel.icio.usでwordpress+pluginsiuseというタグを付けることによってまとめていた。簡単なコメントも付けられるし、URLの変更なんかの修正も簡単でメンテしやすそう。ということで真似して、このblosxomで使っているプラグインをまとめてみた。",
      "author": "Kyo Nagashima (kyo@hail2u.net)",
      "category": "Blosxom",
      "published": "2006-09-29T15:27:00+09:00"
    },
    {
      "title": "Yahoo! Search Web ServicesのJSON(P)を利用したサイト内検索",
      "link": "http://hail2u.net/blog/coding/sitesearch-with-jsonp-of-yahoo-search-web-services.html",
      "id": "tag:hail2u.net,2006:/coding/sitesearch-with-jsonp-of-yahoo-search-web-services",
      "summary": "Yahoo! Search Web ServicesのJSON(P)を利用すれば、JavaScriptのみでサイト内検索が実現できる上、Ajax的にページ遷移無しで検索が実行できる。Google AJAX Searchが内部で利用しているJSONPらしきアレを利用するケースと違い、こちらは公式にアナウンスされているのでおおっぴらに利用できる。というわけで、ほとんど同じタイトルでほとんど同じネタを連続で書いてみる。",
      "author": "Kyo Nagashima (kyo@hail2u.net)",
      "category": "Coding",
      "published": "2006-09-28T16:47:00+09:00"
    }
  ]
};
