#!/usr/bin/env node

"use strict";

require("request").post("https://pubsubhubbub.appspot.com/", {
  form: {
    "hub.mode": "publish",
    "hub.url": process.argv[2]
  }
}, function (error, response) {
  if (response.statusCode !== 204) {
    error = new Error("Hub returned " + response.statusCode + ".");
  }

  if (error) {
    throw error;
  }
});
