#!/usr/bin/env node

'use strict';

var async = require('async');
var fs = require('fs');
var path = require('path');
var spawn = require('child_process').spawn;

var dirRoot = path.resolve(__dirname, '../.grunt/weblog/');
var dirData = path.resolve(dirRoot, 'entries/');
var fileCache = path.resolve(dirRoot, 'plugins/state/files_index.dat');
var dirStatic = path.resolve(__dirname, '../blog/');

var files = fs.readdirSync(dirData).filter(function (dir) {
  if (dir === 'themes') {
    return false;
  }

  return true;
}).map(function (dir) {
  return path.join(dirData, dir, '/index.txt');
});

if (process.argv[2] === '--all') {
  files = files.concat(fs.readFileSync(fileCache, 'utf-8').split(/\r?\n/).filter(function (file) {
    if (file === '') {
      return false;
    }

    return true;
  }).map(function (file) {
    return file.split('=>')[0];
  }));
}

async.eachLimit(files, 16, function (file, next) {
  if (!/\\index\.txt$/.test(file) && !fs.existsSync(file)) {
    console.log('File "' + file + '" not found.');

    return next();
  }

  file = path.relative(dirData, file).replace(/\.txt$/, '.html').replace(/\\/g, '/');
  var html = '';
  var blosxom = spawn('C:/strawberry/perl/bin/perl', [
    'blosxom.cgi',
    'path=/' + file
  ], {
    cwd: dirRoot,
    env: {
      BLOSXOM_CONFIG_DIR: path.resolve(dirRoot)
    }
  });

  blosxom.stdout.on('data', function (data) {
    html += data;
  });

  blosxom.stdout.on('end', function (data) {
    html = html.replace(/^[\s\S]*?\r?\n\r?\n/, '').trimRight() + '\n';
    fs.writeFileSync(path.join(dirStatic, file), html);
  });

  blosxom.on('error', function (error) {
    return next(error);
  });

  blosxom.on('exit', function (code) {
    console.log('File "' + file + '" rebuild.');
    next();
  });
}, function (error) {
  if (error) {
    throw error;
  }
});
