#!/usr/bin/env node

'use strict';

var path = require('path');
var spawn = require('child_process').spawn;

var args = [
  // '-n',
  '-aC',
  '--exclude-from=.rsyncignore',
  '--delete',
  '--progress',
  './',
  'hail2u@s44.xrea.com:~/public_html/hail2u.net/'
];

spawn('rsync', args, {
  cwd: path.resolve(__dirname, '../'),
  stdio: 'inherit'
});
